bot:
  token: "${DISCORD_TOKEN}"
  intents:
    - GUILD_MESSAGES
    - GUILD_MEMBERS
    - MESSAGE_CONTENT
  addonsDir: "./addons"

spring:
  datasource:
    url: "jdbc:sqlite:bot.db"
    driver-class-name: org.sqlite.JDBC
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false