bot:
  token: "${DISCORD_TOKEN}"
  intents:
    - GUILD_MESSAGES
    - GUILD_MEMBERS
    - MESSAGE_CONTENT
  addonsDir: "./addons"

spring:
  datasource:
    url: "jdbc:sqlite:bot.db"
    driver-class-name: org.sqlite.JDBC
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false

---
spring:
  config:
    activate:
      on-profile: mysql
  datasource:
    url: "jdbc:mysql://localhost:3306/nextbot"
    username: "bot"
    password: "secret"
    driver-class-name: com.mysql.cj.jdbc.Driver

---
spring:
  config:
    activate:
      on-profile: mariadb
  datasource:
    url: "jdbc:mariadb://localhost:3306/nextbot"
    username: "bot"
    password: "secret"
    driver-class-name: org.mariadb.jdbc.Driver
